no_permission: '#<ff0000>Nimas dovoljenja za uporabo te komande!'
player_not_found_error: "#<ff0000>Igralca ni na serverju."
tpa_request_player: "#<FFFF00>Prosnja poslana igralcu#<ff0000> %target%#<FFFF00>."
tpa_request_target: "#<ff0000>%player% #<FFFF00>bi se rad teleportiral do tebe.\nDa sprejmes uporabi #<FFA500>/tpaccept#<FFFF00>.\nZa preklic uporabi #<FFA500>/tpdeny#<FFFF00>.\nTa prosnja bo potekla cez #<FFA500>120 sekund#<FFFF00>."
no_requests: "#<FFA500>Napaka: #<ff0000>Nimate cakajocih prosenj."
player_not_found: "#<ff0000>Igralca ni bilo mogoce najti."
tpa_without_args: "#<FFA500>/tpa <player> #<FFFF00>- Poslji prosnjo za teleportacijo dolocenemu igralcu"
tpaccept_player: "#<FFFF00>Igralec je sprejel tvojo prosnjo, teleportacija cez 3 sekunde."
tpconfim_message: "Za sprejem teleportacije klikna na to sporocilo ali pa napisi /tpconfirm"
tpback_message: "Za zavrnitev teleportacije pa klikni na to sporocilo ali pa napisi /tpback."
tpdeny_player: "#<ff0000>%target% #<FFFF00>te je zavrnil."
tpdeny_target: "#<FFFF00>Prosnja zavrnjena."